apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-configmap"
  namespace: "{{ .Values.project.namespace }}"
data:
  DJANGO_DEBUG_MODE: "True"
  DJANGO_ALLOWED_HOSTS: "*"
  DATABASE_ENGINE: "postgresql_psycopg2"
  DJANGO_LOGLEVEL: "info"
  