apiVersion: apps/v1
kind: Deployment
metadata:
  name:  django-lab
  namespace: devops
  labels:
    app:  django-lab
spec:
  selector:
    matchLabels:
      app: django-lab
  replicas: 2
  template:
    metadata:
      labels:
        app:  django-lab
    spec:
      containers:
      - name:  django-lab
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        envFrom:
        - configMapRef:
            name: "{{ .Release.Name }}-configmap"
        - secretRef:
            name: "{{ .Release.Name }}-secrets"
        ports:
        - containerPort:  "{{ .Values.container.port }}"
          name:  django-lab
      restartPolicy: Always