apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secrets"
  namespace: devops
data:
  DJANGO_SECRET_KEY: "{{ .Values.DJANGO_SECRET_KEY | b64enc | quote }}"
  DATABASE_HOST: "{{ .Values.DATABASE_HOST | b64enc | quote }}"
  DATABASE_PORT: "{{ .Values.DATABASE_PORT | b64enc | quote }}"
  DATABASE_USERNAME: "{{ .Values.DATABASE_USERNAME | b64enc | quote }}"
  DATABASE_PASSWORD: "{{ .Values.DATABASE_PASSWORD | b64enc | quote }}"
  DATABASE_NAME: "{{ .Values.DATABASE_NAME | b64enc | quote }}"