apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secrets"
  namespace: "{{ .Release.Namespace }}"

data:
  DJANGO_SECRET_KEY: {{ .Values.django.secretKey | b64enc | quote }}
  DATABASE_HOST: {{ .Values.database.hostname | b64enc | quote }}
  DATABASE_PORT: {{ .Values.database.port | b64enc | quote }}
  DATABASE_USERNAME: {{ .Values.database.username | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.database.password | b64enc | quote }}
  DATABASE_NAME: {{ .Values.database.name | b64enc | quote }}