replicaCount: 1

project:
  name: django-lab
  namespace: devops

image:
  repository: spencer810704/django-lab
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 80
