replicaCount: 1

image:
  repository: spencer810704/django-lab
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

container:
  port: 80
